In [5]:
import numpy as np
import pandas as pd
import sklearn
import random

In [6]:
data = pd.read_csv("dhtreadings.csv")

In [7]:
data = data.iloc[:, 1:3]

In [8]:
data

temperature  humidity
0          22.40        48
1          24.72        78
2          24.72        78
3          24.72        78
4          24.72        78
..           ...       ...
868        35.94        84
869        36.45        86
870        36.45        86
871        36.73        87
872        36.73        87

[873 rows x 2 columns]

In [9]:
data = data.sort_values('temperature')

In [13]:
arr = []
for i in range(len(data)):
    if i <= len(data) // 3:
        arr.append(1)
    elif len(data) // 3 < i <= 2*len(data) // 3:
        arr.append(2)
    elif i > 2*len(data) // 3:
        arr.append(3)
arr_np = np.array(arr)
arr_np = arr_np.reshape((len(data), 1))

In [14]:
data_np = data.to_numpy()

In [15]:
data_new = np.append(data_np, arr_np, axis = 1)

In [16]:
from sklearn.utils import shuffle
data_new = shuffle(data_new)

In [17]:
data_new

array([[24.53, 81.  ,  1.  ],
       [42.92, 95.  ,  3.  ],
       [24.76, 79.  ,  2.  ],
       ...,
       [36.01, 83.  ,  3.  ],
       [24.76, 79.  ,  2.  ],
       [24.72, 78.  ,  1.  ]])

In [18]:
random_ind = np.random.choice([0, 1], size = data_new.shape[0], p = [0.2, 0.8]).astype('bool')
train_data = data_new[random_ind]
test_data = data_new[(1-random_ind).astype('bool')]
x_train = train_data[:, :2]
y_train = train_data[:, 2]
x_test = test_data[:, :2]
y_test = test_data[:, 2]

In [19]:
from sklearn.tree import DecisionTreeClassifier
classifier_decision = DecisionTreeClassifier()
classifier_decision.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [20]:
y_pred = classifier_decision.predict(x_test)

In [21]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[62  0  0]
 [ 2 51  0]
 [ 0  0 59]]
              precision    recall  f1-score   support

         1.0       0.97      1.00      0.98        62
         2.0       1.00      0.96      0.98        53
         3.0       1.00      1.00      1.00        59

    accuracy                           0.99       174
   macro avg       0.99      0.99      0.99       174
weighted avg       0.99      0.99      0.99       174



In [46]:
from sklearn.ensemble import RandomForestClassifier
classifier_random = RandomForestClassifier()
classifier_random.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [47]:
y_pred = classifier_random.predict(x_test)

In [48]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[46  0  0]
 [ 2 69  2]
 [ 0  0 65]]
              precision    recall  f1-score   support

         0.0       0.96      1.00      0.98        46
         1.0       1.00      0.95      0.97        73
         2.0       0.97      1.00      0.98        65

    accuracy                           0.98       184
   macro avg       0.98      0.98      0.98       184
weighted avg       0.98      0.98      0.98       184



In [22]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier()
classifier_knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [23]:
y_pred = classifier_knn.predict(x_test)

In [24]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[61  1  0]
 [ 2 51  0]
 [ 0  2 57]]
              precision    recall  f1-score   support

         1.0       0.97      0.98      0.98        62
         2.0       0.94      0.96      0.95        53
         3.0       1.00      0.97      0.98        59

    accuracy                           0.97       174
   macro avg       0.97      0.97      0.97       174
weighted avg       0.97      0.97      0.97       174



In [25]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(C=1e5)

# Create an instance of Logistic Regression Classifier and fit the data.
logreg.fit(x_train, y_train)

LogisticRegression(C=100000.0, class_weight=None, dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [26]:
y_pred = logreg.predict(x_test)

In [27]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[62  0  0]
 [ 2 51  0]
 [ 0  0 59]]
              precision    recall  f1-score   support

         1.0       0.97      1.00      0.98        62
         2.0       1.00      0.96      0.98        53
         3.0       1.00      1.00      1.00        59

    accuracy                           0.99       174
   macro avg       0.99      0.99      0.99       174
weighted avg       0.99      0.99      0.99       174



In [28]:
my_sample = np.array([24, 80]).reshape(1, -1)

In [29]:
y_pred_1 = logreg.predict(my_sample)